version: '3' 
services: 
    kismet_exporter:
        image: 'zedzed9/kismet_exporter'
        restart: unless-stopped
        ports: 
          - "8501:8501" 
        env_file:
         - ./kismet_exporter.env
