version: '3' 
services: 
    kismet_exporter:
        build: .
        image: 'zedzed9/kismet_exporter'
        restart: unless-stopped
        ports: 
          - "8501:8501" 
        env_file:
         - ./kismet_exporter.env
        volumes:
          - ./pd_lookup/txt:/kis_exp/pd_lookup/txt
